#############################################################################
# Deprovision sqs standard queue
#############################################################################

- name: Remove sqs standard queue
  cloudformation:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    stack_name: "apb-sqs-standard-{{ stack_identifier }}"
    state: "absent"
    region: "{{ region }}"
