- name: sqs standard deprovision
  hosts: localhost
  gather_facts: false
  connection: local
  roles:
  - role: ansible.kubernetes-modules
    install_python_requirements: no
  - role: deprovision-sns-standard-apb-openshift
    playbook_debug: false