apiVersion: v1
kind: Template
metadata:
  name: sqs
parameters:
  - name: namespace
  - name: service_class_name
  - name: stack_identifier
  - name: aws_access_key
  - name: aws_secret_key
  - name: aws_region
objects:
  - apiVersion: servicecatalog.k8s.io/v1alpha1
    kind: Instance
    metadata:
      name: sqs
      namespace: ${namespace}
    spec:
      serviceClassName: ${service_class_name}
      planName: standard
      parameters:
        stack_identifier: ${stack_identifier}
        aws_access_key: ${aws_access_key}
        aws_secret_key: ${aws_secret_key}
        region: ${aws_region}
        DelaySeconds: 5
        MaximumMessageSize: 262144
        MessageRetentionPeriod: 345600
        ReceiveMessageWaitTimeSeconds: "1"
        UsedeadletterQueue: "false"
        VisibilityTimeout: 5
