- include: standard.yml
  when: _apb_plan_id == "standard"

- include: fifo.yml
  when: _apb_plan_id == "fifo"

- name: Encode bind credentials
  asb_encode_binding:
    fields:
      QUEUE_ARN:  "{{ sqs_queue_arn }}"
      QUEUE_NAME: "{{ sqs_queue_name }}"
      QUEUE_URL:  "{{ sqs_queue_url }}"
  when: state == 'present'
