#############################################################################
# SQS Standard Queue
#############################################################################
---
- name: SQS Standard Queue - {{ apb_action }}
  cloudformation:
    stack_name: "apb-sqs-{{ stack_suffix }}"
    state: "{{ state }}"
    region: "{{ region }}"
    disable_rollback: false
    template: "{{ role_path }}/files/SQSStandardQueue.yml"
    template_parameters:
      DelaySeconds: "{{ DelaySeconds | string }}"
      MaximumMessageSize: "{{ MaximumMessageSize | string }}"
      MessageRetentionPeriod: "{{ MessageRetentionPeriod | string }}"
      ReceiveMessageWaitTimeSeconds: "{{ ReceiveMessageWaitTimeSeconds }}"
      UsedeadletterQueue: "{{ UsedeadletterQueue }}"
      VisibilityTimeout: "{{ VisibilityTimeout | string }}"
    tags:
      ServiceBrokerId: "{{ application_name }}"
  register: sqs

- name: Recording SQS standard queue output facts
  set_fact:
    sqs_queue_arn:  "{{ sqs.stack_outputs.QueueARN }}"
    sqs_queue_name: "{{ sqs.stack_outputs.QueueName }}"
    sqs_queue_url:  "{{ sqs.stack_outputs.QueueURL }}"
  when: sqs.stack_outputs is defined
