global:
  parameters: {}
  regions:
    - us-east-1

plans:
  sqs-fifo:
    parameters:
      ContentBasedDeduplication: "true"
      DelaySeconds: 5
      MaximumMessageSize: 262144
      MessageRetentionPeriod: 345600
      ReceiveMessageWaitTimeSeconds: "1"
      UsedeadletterQueue: "false"
      VisibilityTimeout: 5
    sample_app: sqs-sample-app-apb
