- name: sqs-apb deprovision
  hosts: localhost
  gather_facts: false
  connection: local
  environment:
    AWS_ACCESS_KEY_ID: "{{ aws_access_key }}"
    AWS_SECRET_ACCESS_KEY: "{{ aws_secret_key }}"
  vars:
    state: absent
    apb_action: "Deprovisioning"
  roles:
  - role: ansible.kubernetes-modules
    install_python_requirements: no
  - role: ansibleplaybookbundle.asb-modules
  - role: sqs-apb-openshift
    playbook_debug: false